version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "MySql2019!"
      MYSQL_DATABASE: "testedb"
    ports:
      - "3308:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge